baseURL: "https://thisistheway.wiki"
title: thisistheway
paginate: 40
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: thisistheway
  description: "thisistheway"
  author: Peter Dieleman
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]

  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: /favicon.ico
    favicon16x16: /Boba-Fett-16x16.png
    favicon32x32: /Boba-Fett-32x32.png
    apple_touch_icon: /apple-touch-icon.png
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "thisistheway"
    # icon: /boba_fett.png
    # iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: thisistheway
    subtitle: 
      "Hi, I'm Peter Dieleman, a software developer currently living in Dresden, DE.  
      This page contains notes on software development, cooking recipes and other random observations.
      In case you want to reach out to me, you can contact me through the links below.  
      For cat pictures click the Instagram icon."
    # imageUrl: /Boba-Fett-512x512.png
    imageWidth: 100
    imageHeight: 100
    imageTitle: my image
    buttons:
      - name: Cooking Recipes
        url: tags/cooking-recipe
      - name: German
        url: tags/german
      - name: Java
        url: tags/java
      - name: Cat Pics
        url: tags/catpics
      - name: Youtube
        url: tags/youtube

  # home-info mode
  homeInfoParams:
    Title: Personal Wiki
    Content: "Plus some other random observations. Press  Alt + / for search."

  socialIcons:
    - name: github
      url: "https://github.com/peterdieleman"
    - name: twitter
      url: "https://twitter.com/ptrdlmn/"
    - name: linkedin
      url: "https://www.linkedin.com/in/ptrdlmn/"
    - name: strava
      url: "https://www.strava.com/athletes/ptrdlmn"
    - name: instagram
      url: "https://www.instagram.com/annaelsadresden/"
    # - name: stackoverflow
    #   url: "https://stackoverflow.com/users/3513476/thisistheway"
  # analytics:
  #   google:
  #     SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page
  
  editPost:
    URL: "https://github.dev/peterdieleman/papermod/blob/master/content"
    Text: "Edit Post" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 1
    distance: 1000000
    threshold: 0.3
    minMatchCharLength: 0
    includeScore: true
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: What even is this?
      url: /about/
      weight: 10
    - identifier: archive
      name: Posts
      url: /archives/
      weight: 20
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
    - identifier: search
      name: Search
      url: /search/
      weight: 40
    - identifier: edit
      name: New Post
      url: https://github.dev/peterdieleman/papermod/blob/master/content/posts/new.md
      weight: 50

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    style: monokai

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: false
    simple: false
  vimeo:
    disable: true
  youtube:
    disable: false
